### ISSUE TITLE
Battery Connector Colors in Pretty Pins TopSide

### ISSUE THREAD

**Issue by mikeysklar** [adafruit/Adafruit-ESP32-S3-Reverse-TFT-Feather-PCB#1]
[forum issue](https://forums.adafruit.com/viewtopic.php?t=214404) from @Timeline 

The battery connector colors are at a diagonal from each other in the red <--> black when viewing the 2-pin battery JST connector DISPLAY SIDE. Swapping the black and red dots would make things correct.

![Screenshot 2024-10-24 at 9 17 25 AM](https://github.com/user-attachments/assets/a5de4bd0-7314-46fc-acf9-9926a89d7212)

**Comment by ladyada** [comment]
@BlitzCityDIY plz work with @FoamyGuy to have him fix it! (good ez thing)

**Comment by BlitzCityDIY** [comment]
will do! @FoamyGuy when you're working next ping me and we'll chat

**Comment by FoamyGuy** [comment]
This is updated now, thanks for reporting! I left a comment in the linked forum post as well.
